// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DapperDal`
//     Provider:               `System.Data.sqlclient`
//     Connection String:      `Data Source=(local);Initial Catalog=DapperDalDb;Integrated Security=True`
//     Include Views:          `True`

using System;
using Dapper;
using Dapper.Contrib.Extensions;

namespace Dapper_DAL.Models
{
    /// <summary>
    /// A class which represents the Customer table.
    /// </summary>
	[Table("[dbo].[Customer]")]
	public partial class Customer
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual string Address { get; set; }
		public virtual string Zip { get; set; }
		public virtual decimal? Balance { get; set; }
		public virtual DateTime? Registered { get; set; }
	}

}
